project_name: potus

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: potus
    main: ./cmd/potus
    binary: potus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: potus
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: taaha3244
    name: potus
  draft: false
  prerelease: auto
  name_template: "POTUS {{.Version}}"
  header: |
    ## POTUS {{.Version}}

    Power Of The Universal Shell - AI Coding Agent

    ### Installation

    **macOS (Homebrew):**
    ```bash
    brew install potus-cli/tap/potus
    ```

    **Windows (Scoop):**
    ```bash
    scoop bucket add potus https://github.com/potus-cli/scoop-bucket
    scoop install potus
    ```

    **Direct Download:**
    Download the binary for your platform below and add it to your PATH.

    ### What's Changed

brews:
  - name: potus
    repository:
      owner: taaha3244
      name: homebrew-tap
    homepage: https://github.com/taaha3244/potus
    description: "Power Of The Universal Shell - AI Coding Agent"
    license: MIT
    install: |
      bin.install "potus"
    test: |
      system "#{bin}/potus", "--version"

scoop:
  bucket:
    owner: taaha3244
    name: scoop-bucket
  homepage: https://github.com/taaha3244/potus
  description: "Power Of The Universal Shell - AI Coding Agent"
  license: MIT

nfpms:
  - id: potus
    package_name: potus
    vendor: POTUS Contributors
    homepage: https://github.com/taaha3244/potus
    description: "Power Of The Universal Shell - AI Coding Agent"
    license: MIT
    maintainer: Taaha Mushtaq <taaha3244@users.noreply.github.com>
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

dockers:
  - image_templates:
      - "ghcr.io/taaha3244/potus:{{ .Version }}-amd64"
      - "ghcr.io/taaha3244/potus:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Power Of The Universal Shell - AI Coding Agent"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/taaha3244/potus"

  - image_templates:
      - "ghcr.io/taaha3244/potus:{{ .Version }}-arm64"
      - "ghcr.io/taaha3244/potus:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Power Of The Universal Shell - AI Coding Agent"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/taaha3244/potus"

docker_manifests:
  - name_template: ghcr.io/taaha3244/potus:{{ .Version }}
    image_templates:
      - ghcr.io/taaha3244/potus:{{ .Version }}-amd64
      - ghcr.io/taaha3244/potus:{{ .Version }}-arm64

  - name_template: ghcr.io/taaha3244/potus:latest
    image_templates:
      - ghcr.io/taaha3244/potus:latest-amd64
      - ghcr.io/taaha3244/potus:latest-arm64
